### ISSUE TITLE
Using lazycsv in module that is in different directory breaks file reading

### ISSUE THREAD

**Issue by krzysztofspalinski** [Crunch-io/lazycsv#1]
I found a bug (or maybe it's an expected behaviour?) that prevents us from reading csv file when `lazycsv` is used in a module that is in a different folder than script we are running.

## Occurrence example
Easy to reproduce example is shown below.

**Project file structure**
```
./module/exampleclass.py
./script.py
./example.csv
```

**exampleclass.py**
```python3
from lazycsv import lazycsv

class ExampleClass:
    def __init__(self, path):
        self.data = lazycsv.LazyCSV(path)
```

**script.py**
```python3
from module.exampleclass import ExampleClass

if __name__ == "__main__":
    object = ExampleClass('example.csv')
```

When we run `script.py`, following error occurs:

```
FileNotFoundError: unable to open data file, check to be sure that the user has read permissions and/or ownership of the file, and that the file exists.
```

## Why it happens? 
From my understanding, it happens because of the way the function `_FullName_FromName` is defined. In that function, `_dirname` is created using Python's `__file__` variable, which contains path to the module, and not the file in which we imported the module. 

## How to fix it?
I think that defining `_dirname` using `os.getcwd()` would solve this issue.

**Comment by 1mikegrn** [comment]
I'll have to think about this more, the solution isn't as straight forward as doing `os.getcwd()` because, if for example you're running this example script from any other directory it'll also not work (or, and more importantly, if you clone the repo and run `pytest` from the repo root instead of within the `test` folder, the test suite doesn't pass, for the same reason). 

As you noticed, the current implementation uses the path of the the calling file as the anchor for which relative imports are resolved, which is why passing the variable directly from an encapsulating class doesn't work for relative filepaths (though it should work if you pass an absolute filepath to `ExampleClass`).

I'll look around to see if there are solutions to this however, and get back to you.

**Comment by 1mikegrn** [comment]
Pushed a fix which should resolve the issue without breaking backwards compatibility, see v1.1.4
